### ISSUE TITLE
Deploy the API through the Kubernetes

### ISSUE THREAD

**Issue by pford68** [giantmachines/biblio-api#27]
Added a deployment YAML for the Deployment and a Service.  Added an ingress resource YAML that maps a path to the Biblio K8s service.

**Comment by pford68** [comment]
Successfully deployed to Digital Ocean with K8s.

**Comment by pford68** [comment]
### Ingress Resource
Originally, I did not set the application context, so the path to the "get all books" endpoint was simply "/books."  However, I wanted a different path publicly:  `/api/v1/books`.

Therefore, I had to re-write the path in the ingress-resource, to translate the requested path (/api/v1/books) to the resource represented by `/books`:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: biblio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /api/v1(/|$)(.*)
            backend:
              serviceName: biblio-svc
              servicePort: 80
```

**Comment by pford68** [comment]
Eventually, I decided to make things simple and to update the context path to begin with `api/v1`.   I did that in _application.properties_.   That meant that the URL re-write would no longer be needed; in fact, it would not work.

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: biblio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api/v1
            backend:
              serviceName: biblio-svc
              servicePort: 80
```
